### ISSUE TITLE
Player position inconsistent

### ISSUE THREAD

**Issue by CylonicRaider** [Daniel300/Explorinator#5]
The mini-map from scouting and the "overall" map show different player positions (mini-map position is shifted by one cell to the bottom-right, if compared to the large maps).

**Comment by TauNeutrin0** [comment]
The player position was being marked incorrectly by the printVisMap(...) method. The position was marked as (vis,vis) not (vis-1,vis-1). Also fixed earlier attempt at fix where visibility algorithm was deliberately being shifted to match.

Fixed with commit 266e705
